Repository APPS-sookmyung/2024-WELLET-client, pull requests merged in 2024-09, with the labels that each got.

#75 Feat: 명함 2장 등록 및 디테일 수정
  src/components/CardInfo/CardInfo.jsx
  src/components/SearchBar/SearchBar.jsx
  src/constants/cardData.js
  src/constants/cardsSampleData.js
  src/nextDevelopItems/EmailLoginPage/EmailLoginPage.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 💫 feature, 🎨 UI

#77 Merge: dev to main
  src/assets/icons/index.js
  src/assets/icons/nav_add_card.svg
  src/assets/icons/nav_add_card_active.svg
  src/assets/icons/nav_home.svg
  src/assets/icons/nav_home_active.svg
  src/assets/icons/nav_mypage.svg
  src/assets/icons/nav_mypage_active.svg
  src/assets/icons/nav_view_card.svg
  src/assets/icons/nav_view_card_active.svg
  src/components/CardInfo/CardInfo.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/TabBar/TabBar.jsx
  src/components/TabBar/TabBar.style.jsx
  src/constants/cardData.js
  src/constants/cardsSampleData.js
  src/nextDevelopItems/EmailLoginPage/EmailLoginPage.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🌏 deploy

#78 Feat: 그룹수정 모달 띄우기 구현
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 💫 feature

#79 Fix: 프로필이미지 편집 오류 해결
  src/assets/icons/icon.svg
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 🔧 Fix

#80 Feat: 그룹뱃지 컴포넌트 구현 및 수정
  src/components/BadgeDetail/BadgeDetail.jsx
  src/components/BadgeDetail/BadgeDetail.style.jsx
  src/components/BadgeDetail/index.js
  src/components/index.js
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 💫 feature

#85 #83 [DOCS] README.md 및 PR 템플릿 수정
  .github/pull_request_template.md
  README.md
Labels: 📃 docs

#84 #83 [DOCS] PR 템플릿 생성
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
Labels: 📃 docs

#86 #83 [DOCS] 이슈 템플릿 내 타이틀 추가
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
Labels: 📃 docs

#81 [FEAT] 그룹 API 기본 셋팅
  package.json
  src/apis/group.js
  src/apis/index.js
  src/axios/index.js
  src/components/AddGroupModal/AddGroupModal.jsx
  src/dummy/user.js
  src/main.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 📬 API

#87 [MERGE] dev to main
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  .github/pull_request_template.md
  README.md
  package.json
  src/apis/group.js
  src/apis/index.js
  src/assets/icons/icon.svg
  src/axios/index.js
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/BadgeDetail/BadgeDetail.jsx
  src/components/BadgeDetail/BadgeDetail.style.jsx
  src/components/BadgeDetail/index.js
  src/components/index.js
  src/dummy/user.js
  src/main.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 🌏 deploy

#88 #83 [DOCS] README.md 수정
  .github/ISSUE_TEMPLATE/feature-request.md
  README.md
Labels: 📃 docs
