Repository APPS-sookmyung/2024-WELLET-client, pull requests merged in 2024-08, with the labels that each got.

#43 Feat: mypage 수정
  src/icons/icon-arrow-down.svg
  src/icons/icon-arrow.svg
  src/icons/icon-pencil2.svg
  src/icons/icon-x.svg
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
Labels: 💫 feature

#46 Merge: dev to main
  index.html
  public/favicon-196x196.png
  public/manifest.json
  src/icons/icon-arrow-down.svg
  src/icons/icon-arrow.svg
  src/icons/icon-pencil2.svg
  src/icons/icon-x.svg
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: 🌏 deploy

#47 Fix: 마이페이지 css 수정
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
Labels: 🔧 Fix

#50 Feat: 그룹 추가 모달 컴포넌트 구현
  src/assets/icon.svg
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/AddGroupModal/AddGroupModal.style.jsx
  src/components/AddGroupModal/index.js
  src/components/Badge/BlueBadge.jsx
  src/components/Badge/BlueBadge.style.jsx
  src/components/InputWrapper/InputWrapper.jsx
  src/components/InputWrapper/InputWrapper.style.jsx
  src/components/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 💫 feature

#52 Modify: PR 템플릿 내 항목 추가
  .github/pull_request_template.md
Labels: 📃 docs

#53 Feat: 메인페이지 - 내 명함 넘기기 모션 구현
  src/assets/icon.svg
  src/components/CardInfo/CardInfo.jsx
  src/components/Icon/index.js
  src/components/MyCard/MyCard.jsx
  src/components/MyCard/MyCard.style.jsx
  src/components/MyCard/index.js
  src/components/index.js
  src/constants/myCardData.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/utils/HomePageUtils/homePageEffects.js
  src/utils/HomePageUtils/homePageUtils.js
Labels: 💫 feature, 🎨 UI

#55 Feat: 명함 상세보기 페이지 정보 구현
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
Labels: 💫 feature

#56 Feat: 마이페이지 컴포넌트명 및 위치 조정, QR 코드 모달 구현
  src/assets/icon.svg
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
Labels: 💫 feature, 🎨 UI

#57 Docs: README.md 수정
  README.md
Labels: 📃 docs

#61 Docs: PR 템플릿 내 체크리스트 추가
  .github/pull_request_template.md
  README.md
Labels: 📃 docs

#60 Feat: 명함 상세보기 페이지 수정 및 카드 인포 링크 수정
  src/components/CardInfo/CardInfo.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/DetailEditPage/index.js
  src/pages/index.js
  src/router.jsx
Labels: 🔧 Fix

#62 Fix: 마이페이지편집 css 수정
  src/pages/MyPageEdit/MyPageEdit.jsx
  src/pages/MyPageEdit/MyPageEdit.style.jsx
  src/pages/MyPageEdit/index.js
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
Labels: 🔧 Fix

#64 Fix: 로고 컬러는 props로 전달하지 않아서 생기는 오류 해결
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🔧 Fix

#65 Feat: 명함을 오름차순 정렬하여 명함 보기 페이지에 목록 띄우기
  src/components/CardInfo/CardInfo.style.jsx
  src/constants/cardData.js
  src/constants/cardsSampleData.js
  src/constants/myCardData.js
  src/constants/myCardSampleData.js
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/utils/HomePageUtils/homePageEffects.js
  src/utils/HomePageUtils/homePageUtils.js
Labels: 💫 feature

#63 Style: 명함보기 페이지 내 아이콘 등 디테일 수정
  src/assets/icon.svg
  src/components/CardInfo/CardInfo.jsx
  src/components/CardInfo/CardInfo.style.jsx
  src/components/MyCard/MyCard.style.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 🔧 Fix

#66 Modify: 홈 페이지 내 명함 카드 수정
  src/assets/images/onboarding_2.svg
  src/assets/images/onboarding_3.svg
  src/components/MyCard/MyCard.jsx
  src/components/MyCard/MyCard.style.jsx
  src/constants/myCardSampleData.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/utils/HomePageUtils/homePageEffects.js
  src/utils/HomePageUtils/homePageUtils.js
Labels: 🎨 UI, 🔧 Fix

#67 Fix: 탭바 깜박임 오류 해결 & 불필요한 버튼 제거
  src/components/Layout/Layout.jsx
  src/components/Layout/index.js
  src/components/index.js
  src/main.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/router.jsx
  src/utils/HomePageUtils/homePageUtils.js
Labels: ♻️ refactor, 🔧 Fix

#68 Test: 아이폰 safe-area 처리 테스트(1)
  index.html
  src/components/TabBar/TabBar.style.jsx
Labels: ✅ test, 🎨 UI

#69 Fix: 상세보기,편집 css 수정 및 오류 해결
  src/constants/cardData.js
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/MyPage/MyPage.jsx
Labels: 🔧 Fix

#71 Fix: 탭바 높이 수정
  src/assets/icons/icon.svg
  src/assets/icons/step_1.svg
  src/assets/icons/step_2.svg
  src/assets/icons/step_3.svg
  src/components/Icon/Icon.jsx
  src/components/TabBar/TabBar.style.jsx
  src/constants/onboarding.js
  src/icons/icon-arrow-down.svg
  src/icons/icon-arrow-right.svg
  src/icons/icon-arrow.svg
  src/icons/icon-call.svg
  src/icons/icon-dot3.svg
  src/icons/icon-gallery.svg
  src/icons/icon-magnifying-glass.svg
  src/icons/icon-mail.svg
  src/icons/icon-message.svg
  src/icons/icon-more.svg
  src/icons/icon-pencil.svg
  src/icons/icon-pencil2.svg
  src/icons/icon-share.svg
  src/icons/icon-x.svg
  src/icons/logo.svg
Labels: 🎨 UI, 🔧 Fix

#72 Merge: dev to main
  src/assets/icons/icon.svg
  src/assets/icons/step_1.svg
  src/assets/icons/step_2.svg
  src/assets/icons/step_3.svg
  src/components/Icon/Icon.jsx
  src/components/TabBar/TabBar.style.jsx
  src/constants/onboarding.js
  src/icons/icon-arrow-down.svg
  src/icons/icon-arrow-right.svg
  src/icons/icon-arrow.svg
  src/icons/icon-call.svg
  src/icons/icon-dot3.svg
  src/icons/icon-gallery.svg
  src/icons/icon-magnifying-glass.svg
  src/icons/icon-mail.svg
  src/icons/icon-message.svg
  src/icons/icon-more.svg
  src/icons/icon-pencil.svg
  src/icons/icon-pencil2.svg
  src/icons/icon-share.svg
  src/icons/icon-x.svg
  src/icons/logo.svg
Labels: 🌏 deploy

#73 Modify: TabBar에 수정사항 적용
  src/assets/icons/index.js
  src/assets/icons/nav_add_card.svg
  src/assets/icons/nav_add_card_active.svg
  src/assets/icons/nav_home.svg
  src/assets/icons/nav_home_active.svg
  src/assets/icons/nav_mypage.svg
  src/assets/icons/nav_mypage_active.svg
  src/assets/icons/nav_view_card.svg
  src/assets/icons/nav_view_card_active.svg
  src/components/TabBar/TabBar.jsx
  src/components/TabBar/TabBar.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
Labels: 🎨 UI
