Repository APPS-sookmyung/2024-WELLET-client, pull requests merged in 2024-07, with the labels that each got.

#5 modify: 라우터 등 개발 환경 세팅
  index.html
  package.json
  src/App.css
  src/App.jsx
  src/main.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/index.js
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/HomePage/index.js
  src/pages/HomePage/styles.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPage/index.js
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
  src/pages/ViewCardPage/index.js
  src/pages/index.js
  src/router.jsx
  src/styles/index.js
  src/styles/pretendardFont.style.js
  src/styles/resetStyles.style.js
  src/styles/welletStyles.style.js
  vite.config.js
  yarn.lock
Labels: ⚙ setting

#6 feat: 명함 보기 페이지 구현
  src/icons/icon-arrow-right.svg
  src/icons/icon-magnifying-glass.svg
  src/icons/icon-more.svg
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
  src/router.jsx
Labels: 💫 feature, 🎨 UI

#7 feat: 명함 추가 페이지 구현
  icon-add-card-dot.svg
  src/icons/icon-add-card-dot.svg
  src/icons/icon-add-card.svg
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 💫 feature, 🎨 UI

#9 feat: 헤더 컴포넌트 생성
  src/components/Header/Header.jsx
  src/components/Header/Header.style.jsx
  src/components/Header/NavBar.jsx
  src/components/Header/index.js
  src/components/Header/styles.js
  src/components/index.js
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/OnBoardingPage/OnBoardingPage.jsx
  src/pages/OnBoardingPage/OnBoardingPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/router.jsx
Labels: 💫 feature, ♻️ refactor, 🎨 UI

#10 docs: pr 템플릿 추가
  .github/pull_request_template.md
  icon-add-card-dot.svg
Labels: 📃 docs

#11 feat: 하단 탭바 구현
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/styles.js
  src/components/TabBar/TabBar.jsx
  src/components/TabBar/TabBar.style.jsx
  src/components/TabBar/index.js
  src/components/index.js
  src/icons/icon-nav-add-card.svg
  src/icons/icon-nav-home.svg
  src/icons/icon-nav-mypage.svg
  src/icons/icon-nav-view-card.svg
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/router.jsx
Labels: 💫 feature, 🎨 UI

#12 feat: 검색창 컴포넌트 생성 및 적용
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.style.jsx
  src/components/SearchBar/index.js
  src/components/index.js
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 💫 feature, 🎨 UI

#13 feat: 버튼 컴포넌트 구현
  src/components/Button/BlueButton.jsx
  src/components/Button/BlueButton.style.jsx
  src/components/Button/PrimaryButton.jsx
  src/components/Button/PrimaryButton.style.jsx
  src/components/Button/SecondaryButton.jsx
  src/components/Button/SecondaryButton.style.jsx
  src/components/Button/index.js
  src/components/index.js
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/styles/welletStyles.style.js
Labels: 💫 feature, 🎨 UI

#14 feat: 명함 추가 페이지 구현 및 input 컴포넌트 생성
  src/components/InputWrapper/InputWrapper.jsx
  src/components/InputWrapper/InputWrapper.style.jsx
  src/components/InputWrapper/index.js
  src/components/index.js
  src/icons/icon-image.svg
  src/icons/icon-pencil.svg
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
Labels: 💫 feature, 🎨 UI

#16 modify: 탭바 활성화시 아이콘 색상 변경
  src/components/SearchBar/SearchBar.style.jsx
  src/components/TabBar/TabBar.jsx
  src/icons/icon-magnifying-glass.svg
  src/icons/icon-nav-add-card-active.svg
  src/icons/icon-nav-home-active.svg
  src/icons/icon-nav-mypage-active.svg
  src/icons/icon-nav-view-card-active.svg
Labels: 🎨 UI

#18 dev to main
  src/components/CardInfo/CardInfo.jsx
  src/components/CardInfo/CardInfo.style.jsx
  src/components/CardInfo/index.js
  src/components/SearchBar/SearchBar.style.jsx
  src/components/TabBar/TabBar.jsx
  src/components/index.js
  src/icons/icon-magnifying-glass.svg
  src/icons/icon-nav-add-card-active.svg
  src/icons/icon-nav-home-active.svg
  src/icons/icon-nav-mypage-active.svg
  src/icons/icon-nav-view-card-active.svg
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 🌏 deploy

#19 modify: 명함 카드 내 폰트 사이즈 등 디테일 수정
  src/components/CardInfo/CardInfo.style.jsx
  src/components/Header/Header.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🎨 UI

#22 Modify: initial-scale 값 및 CSS 속성 일부 수정
  index.html
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/styles/welletStyles.style.js
Labels: 🎨 UI

#23 Merge: dev to main
  index.html
  src/components/CardInfo/CardInfo.style.jsx
  src/components/Header/Header.style.jsx
  src/icons/icon-call.svg
  src/icons/icon-dot3.svg
  src/icons/icon-gallery.svg
  src/icons/icon-mail.svg
  src/icons/icon-message.svg
  src/icons/icon-share.svg
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/styles/welletStyles.style.js
Labels: 🌏 deploy

#27 feat: Login, Email Login 뷰 구현
  package.json
  src/assets/icon.svg
  src/assets/imgs/email_login_background.svg
  src/assets/imgs/login_background_circles.svg
  src/assets/imgs/login_background_lines.svg
  src/components/Button/PrimaryButton.jsx
  src/pages/EmailLoginPage/EmailLoginPage.jsx
  src/pages/EmailLoginPage/EmailLoginPage.style.jsx
  src/pages/EmailLoginPage/index.js
  src/pages/FindIdPwPage/FindIdPwPage.jsx
  src/pages/FindIdPwPage/FindIdPwPage.style.jsx
  src/pages/FindIdPwPage/index.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.styles.jsx
  src/pages/LoginPage/index.js
  src/pages/LoginPage/styles.js
  src/pages/index.js
  src/router.jsx
Labels: 💫 feature

#28 modify: 폰트사이즈 크기 조정
  src/assets/icon.svg
  src/assets/images/email_login_background.svg
  src/assets/images/login_background_circles.svg
  src/assets/images/login_background_lines.svg
  src/assets/images/onboarding_1.svg
  src/assets/images/onboarding_2.svg
  src/assets/images/onboarding_3.svg
  src/assets/images/profile-img-default.svg
  src/components/Badge/BlueBadge.jsx
  src/components/Badge/BlueBadge.style.jsx
  src/components/Badge/index.js
  src/components/Button/BlueButton.jsx
  src/components/Button/index.js
  src/components/CardInfo/CardInfo.jsx
  src/components/CardInfo/CardInfo.style.jsx
  src/components/InputWrapper/InputWrapper.jsx
  src/components/InputWrapper/InputWrapper.style.jsx
  src/components/index.js
  src/constants/onboarding.js
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/EmailLoginPage/EmailLoginPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
  yarn.lock
Labels: 🎨 UI

#29 Feat: 이미지 가져오기 기능 구현
  src/assets/icon.svg
  src/components/Badge/BlueBadge.style.jsx
  src/icons/icon-add-card-dot.svg
  src/icons/icon-add-card.svg
  src/icons/icon-image.svg
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
Labels: 💫 feature

#30 Feat: 명함 보기 페이지 내 삭제 기능 구현
  src/assets/icon.svg
  src/components/CardInfo/CardInfo.jsx
  src/components/CardInfo/CardInfo.style.jsx
  src/constants/cardData.js
  src/constants/cards.js
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 💫 feature

#31 Modify: 아이콘 컴포넌트화
  src/assets/icon.svg
  src/components/TabBar/TabBar.jsx
  src/components/TabBar/TabBar.style.jsx
  src/icons/icon-nav-add-card-active.svg
  src/icons/icon-nav-add-card.svg
  src/icons/icon-nav-home-active.svg
  src/icons/icon-nav-home.svg
  src/icons/icon-nav-mypage-active.svg
  src/icons/icon-nav-mypage.svg
  src/icons/icon-nav-view-card-active.svg
  src/icons/icon-nav-view-card.svg
Labels: 🎨 UI

#32 Style: props에 따라 검색창 변경
  src/assets/icon.svg
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.style.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🎨 UI

#33 Style: 로고 컴포넌트화
  src/assets/icon.svg
  src/components/Header/Header.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 💫 feature, ♻️ refactor

#35 Feat: favicon 및 README.md 업데이트
  .github/pull_request_template.md
  README.md
  index.html
  src/assets/images/favicon-wellet.png
  src/assets/images/logo-description-wellet.png
  src/assets/images/logo-wellet.png
Labels: 📃 docs, 💫 feature

#36 Style: 그룹이 많아질 경우 생성되는 스크롤바 숨김
  src/components/CardInfo/CardInfo.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 🎨 UI

#37 merge: dev to main
  .github/pull_request_template.md
  README.md
  index.html
  src/assets/images/favicon-wellet.png
  src/assets/images/logo-description-wellet.png
  src/assets/images/logo-wellet.png
  src/components/CardInfo/CardInfo.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 🌏 deploy

#38 Feat: 메타태그 작성
  index.html
Labels: 💫 feature

#39 Feat: 명함 추가 페이지 내 프로필 사진 등록 기능 구현
  src/pages/AddCardPage/AddCardPage.jsx
Labels: 💫 feature

#40 Feat: 명함 추가 페이지 내 drag & drop 기능 구현
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
Labels: 💫 feature

#41 Refactor: 명함 추가 페이지 내 직접 입력 항목 리팩토링
  src/pages/AddCardPage/AddCardPage.jsx
Labels: ♻️ refactor

#42 Feat: PWA 구현
  index.html
  public/favicon-196x196.png
  public/manifest.json
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: 💫 feature
