Repository APPS-sookmyung/2024-WELLET-client, pull requests merged in 2024-11, with the labels that each got.

#97 #91 [FEAT] 그룹 조회/생성/삭제 API 연결
  src/apis/group.js
  src/apis/index.js
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/AddGroupModal/AddGroupModal.style.jsx
  src/components/Badge/BlueBadge.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 📬 API, 💫 feature

#103 #98 [FEAT] 남 명함 사진 수정 구현
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
Labels: 💫 feature

#105 #104 [FEAT] CORS 에러 처리 및 임시 토큰 헤더 추가
  .gitignore
  src/axios/index.js
  vite.config.js
Labels: 📬 API
