Repository APPS-sookmyung/2024-WELLET-client, pull requests merged in 2025-03, with the labels that each got.

#175 #174 [MODIFY] 이메일 필수값 제거, 그룹 필수값 추가
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/AddCardPage/inputFields.js
Labels: 🔧 Fix

#177 #173 [FEAT] 토큰 만료시 '/login'으로 navigate
  src/axios/index.js
  src/main.jsx
Labels: 💫 feature

#181 #180 [FIX] 업로드 가능한 이미지는 1장만 되도록 문구 수정
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
Labels: 🔧 Fix

#188 #183 [DESIGN] 기본 폰트사이즈 11px >> 14px로 수정
  src/components/AddGroupModal/AddGroupModal.style.jsx
  src/components/Badge/BlueBadge.style.jsx
  src/components/Button/PrimaryButton.style.jsx
  src/components/Button/SecondaryButton.style.jsx
  src/components/CardInfo/CardInfo.style.jsx
  src/components/InputWrapper/InputWrapper.style.jsx
  src/components/MyCard/MyCard.style.jsx
  src/components/OnboardingContent/OnboardingContent.style.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.style.jsx
  src/components/TabBar/TabBar.style.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 🎨 UI

#189 #183 [FEAT] 휴대폰 번호 정규화 적용
  src/pages/AddCardPage/AddCardPage.jsx
Labels: 💫 feature

#191 #182 [FIX] 이미지 드래그 앤 드롭 기능 구현
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
Labels: 🔧 Fix

#192 #186 [FEAT] OCR 로딩 효과 구현 ocr loading 효과 구현
  src/components/Header/Header.jsx
  src/components/ImageUploadOverlay/ImageUploadOverlay.jsx
  src/components/ImageUploadOverlay/ImageUploadOverlay.style.jsx
  src/components/ImageUploadOverlay/index.js
  src/components/InputWrapper/InputWrapper.jsx
  src/components/index.js
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
Labels: 💫 feature

#193 #185 [FEAT] 명함 추가 페이지에서 그룹 편집 모달 기능 구현
  src/apis/index.js
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
Labels: 💫 feature

#195 #194 [FIX] 첨부한 명함 이미지 있을 경우에도, 이미지 수정을 위해 버튼 유지
  src/pages/AddCardPage/ImageInputForm.jsx
Labels: 🔧 Fix

#196 [MERGE] dev to main
  src/apis/cards.js
  src/apis/index.js
  src/apis/ocr.js
  src/axios/index.js
  src/components/AddGroupModal/AddGroupModal.style.jsx
  src/components/Badge/BlueBadge.jsx
  src/components/Badge/BlueBadge.style.jsx
  src/components/Button/PrimaryButton.style.jsx
  src/components/Button/SecondaryButton.style.jsx
  src/components/CardInfo/CardInfo.style.jsx
  src/components/Header/Header.jsx
  src/components/ImageUploadOverlay/ImageUploadOverlay.jsx
  src/components/ImageUploadOverlay/ImageUploadOverlay.style.jsx
  src/components/ImageUploadOverlay/index.js
  src/components/InputWrapper/InputWrapper.jsx
  src/components/InputWrapper/InputWrapper.style.jsx
  src/components/MyCard/MyCard.jsx
  src/components/MyCard/MyCard.style.jsx
  src/components/OnboardingContent/OnboardingContent.style.jsx
  src/components/SearchBar/SearchBar.jsx
  src/components/SearchBar/SearchBar.style.jsx
  src/components/TabBar/TabBar.style.jsx
  src/components/index.js
  src/main.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
  src/pages/AddCardPage/inputFields.js
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.style.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/pages/ViewCardPage/ViewCardPage.style.jsx
Labels: 🌏 deploy

#198 #197 [FIX] 이미지 1MB 이상의 파일도 업로드 가능하도록 수정
  src/pages/AddCardPage/ImageInputForm.jsx
Labels: 🔧 Fix

#199 #184 [FIX] 이미지 추가 영역을 선택해도 이미지 추가가 되도록 수정
  src/pages/AddCardPage/ImageInputForm.jsx
Labels: 🔧 Fix

#203 #190 [FIX] 상세보기 언더바 위치 재조정
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/MyPage/MyPage.style.jsx
Labels: 💫 feature

#200 #176 [FEAT] 명함 이미지 추가 및 수정 기능
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
Labels: 📬 API, 💫 feature

#207 #205 [FIX] 그룹 목록에 `flex-wrap: wrap` 속성 적용
  src/pages/AddCardPage/AddCardPage.style.jsx
Labels: 🔧 Fix

#208 #206 [REMOVE] 명함 추가 페이지 내 검색창 삭제
  src/pages/AddCardPage/AddCardPage.jsx
Labels: 🔧 Fix

#210 #209 [DESIGN] 폰트 사이즈 및 문구 변경
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🎨 UI

#211 #204 [FIX] 명함 내 편집할 항목들 폰트 수정
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
Labels: 🎨 UI

#214 #212 [FEAT] 속한 그룹이 없을 때 조건 처리
  src/pages/CardDetailPage/CardDetailPage.jsx
Labels: 💫 feature

#215 #213 [FEAT] 아이콘에 전화/문자/메일 액션 연결
  src/pages/CardDetailPage/CardDetailPage.jsx
Labels: 💫 feature

#218 #217 [FIX] 자잘한 퍼블리싱 오류 해결
  src/components/Header/Header.jsx
  src/components/MyCard/MyCard.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/utils/HomePageUtils/formatPhoneNumber.js
Labels: 🎨 UI, 🔧 Fix

#219 [MERGE] dev to main
  src/components/Header/Header.jsx
  src/components/MyCard/MyCard.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/AddCardPage.style.jsx
  src/pages/AddCardPage/ImageInputForm.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/utils/HomePageUtils/formatPhoneNumber.js
Labels: 🌏 deploy

#221 #220 [FIX] 쓰레기통 아이콘 안 뜨는 오류 해결
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🎨 UI, 🔧 Fix

#222 [MERGE] dev to main
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🌏 deploy

#224 #223 [FIX] 퍼블리싱 오류 수정
  src/apis/cards.js
  src/apis/group.js
  src/apis/myCard.js
  src/apis/ocr.js
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/Badge/BlueBadge.jsx
  src/components/CardInfo/CardInfo.jsx
  src/components/MyCard/MyCard.style.jsx
  src/nextDevelopItems/EmailLoginPage/EmailLoginPage.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🎨 UI, 🔧 Fix

#225 [MERGE] dev to main
  src/apis/cards.js
  src/apis/group.js
  src/apis/myCard.js
  src/apis/ocr.js
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/Badge/BlueBadge.jsx
  src/components/CardInfo/CardInfo.jsx
  src/components/MyCard/MyCard.style.jsx
  src/nextDevelopItems/EmailLoginPage/EmailLoginPage.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🌏 deploy

#227 #226 [FIX] 퍼블리싱 오류 수정
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
Labels: 🎨 UI, 🔧 Fix

#233 #231 [MODIFY] CardInfo에서 회사 정보도 띄우도록
  src/components/CardInfo/CardInfo.jsx
  src/components/MyCard/MyCard.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🎨 UI, 🔧 Fix

#235 #234 [FEAT] 명함 최신 추가 순으로 정렬
  src/components/MyCard/MyCard.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 💫 feature

#236 [MERGE] dev to main
  src/components/CardInfo/CardInfo.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 🌏 deploy

#237 #232 [FIX] 명함 사진 업로드시 미리보기 잘 뜨도록, alert 기능 추가, 디자인 수정
  src/components/MyCard/MyCard.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
Labels: 💫 feature, 🔧 Fix

#238 [MERGE] dev to main
  src/components/MyCard/MyCard.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
Labels: 🌏 deploy

#240 #239 [FIX] 사진 수정 alert창 조건 수정
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 🔧 Fix

#241 [MERGE] dev to main
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 🌏 deploy

#242 #239 [FIX] 사진 수정 alert창 조건 수정(2)
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 🔧 Fix

#243 dev to main
  src/pages/DetailEditPage/DetailEditPage.jsx
Labels: 🌏 deploy
