Repository APPS-sookmyung/2024-WELLET-client, pull requests merged in 2025-02, with the labels that each got.

#146 #145 [MODIFY] API 기본 셋팅 변경
  .yarn/install-state.gz
  src/apis/cards.js
  src/apis/group.js
  src/apis/index.js
  src/apis/myCard.js
  src/axios/index.js
  src/components/CardInfo/CardInfo.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  yarn.lock
Labels: 📬 API, 🔧 Fix

#150 #147 [FEAT] 그룹 생성/삭제 API 연결
  src/assets/icons/icon.svg
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/AddGroupModal/AddGroupModal.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
Labels: 📬 API, 💫 feature

#152 #149 [FEAT] 검색 API 연결
  src/components/SearchBar/SearchBar.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 📬 API, 💫 feature

#153 #99 [FEAT] 내 명함 프로필 수정
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
Labels: 📬 API, 💫 feature

#154 #115 [FEAT] 명함 직접 추가 및 해당 페이지 내 그룹명 조회 API 연동
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 📬 API

#158 #155 [FEAT] 명함등록 페이지 쿼리 스트링 구현
  src/pages/AddCardPage/AddCardPage.jsx
Labels: 💫 feature

#160 #156 [FEAT] `직책`과 `부서`가 모두 있는 경우에만 슬래시(`/`) 삽입
  src/components/CardInfo/CardInfo.jsx
Labels: 💫 feature

#162 #159 [FIX] 홈 화면, 그룹 관련 퍼블리싱 오류 해결
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/MyCard/MyCard.jsx
  src/components/MyCard/MyCard.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/HomePage/HomePage.jsx
Labels: 🎨 UI, 🔧 Fix

#163 #159 [STYLE] 홈 화면 둘러보기에 스크롤 없도록 최대 명함 개수 계산 로직 추가
  src/pages/HomePage/HomePage.jsx
  src/utils/HomePageUtils/homePageUtils.js
Labels: 🎨 UI

#164 #157 [FEAT] 명함 동시 삭제 api 연결
  src/apis/cards.js
  src/apis/index.js
  src/pages/ViewCardPage/ViewCardPage.jsx
Labels: 📬 API, 💫 feature

#165 #99 [FEAT] 내 명함 프로필이미지 api 수정 반영 및 아이콘 제거
  src/apis/index.js
  src/apis/myCard.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
Labels: 📬 API, 💫 feature

#167 [MERGE] dev to main
  .yarn/install-state.gz
  src/apis/cards.js
  src/apis/group.js
  src/apis/index.js
  src/apis/myCard.js
  src/assets/icons/icon.svg
  src/axios/index.js
  src/components/AddGroupModal/AddGroupModal.jsx
  src/components/AddGroupModal/AddGroupModal.style.jsx
  src/components/Badge/BlueBadge.jsx
  src/components/CardInfo/CardInfo.jsx
  src/components/MyCard/MyCard.jsx
  src/components/MyCard/MyCard.style.jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/AddCardPage/AddCardPage.jsx
  src/pages/AddCardPage/DirectInputForm.jsx
  src/pages/CardDetailPage/CardDetailPage.jsx
  src/pages/CardDetailPage/CardDetailPage.style.jsx
  src/pages/DetailEditPage/DetailEditPage.jsx
  src/pages/DetailEditPage/DetailEditPage.style.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPage.style.jsx
  src/pages/MyPageEditPage/MyPageEditPage.jsx
  src/pages/MyPageEditPage/MyPageEditPage.style.jsx
  src/pages/ViewCardPage/ViewCardPage.jsx
  src/utils/HomePageUtils/homePageUtils.js
  yarn.lock
Labels: 🌏 deploy
